[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
recipe_anchor_app = "BnbRLAnvdutKLxFvtcsT5fCdgeMoV1reHfag2TeEreCA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/codespace/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
