[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
recipe_anchor_app = "6xpX3GHGBP7JcEAMuGhhFLxQy16RMESnNjnJteiSHu8X"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/brettgalvez/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
